# Site settings
title: Richard Tzeng
email: rtzeng@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is the bottom of the page. Always learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thefront.github.com" # the base hostname & protocol for your site
github_username:  thefront

# Build settings
markdown: kramdown
